# CREATED BY Bruno Scholz 
services:

#OWASP Juice-Shop
# reference: https://pwning.owasp-juice.shop/companion-guide/latest/part1/running.html
  juice-shop:
    image: "bkimminich/juice-shop"
    container_name: "OWASP-JuiceShop"
    ports:
      - "3000:3000"
    networks: ["owasp_net"]

#  _   _      _                      _        
# | \ | |    | |                    | |       
# |  \| | ___| |___      _____  _ __| | _____ 
# | . ` |/ _ \ __\ \ /\ / / _ \| '__| |/ / __|
# | |\  |  __/ |_ \ V  V / (_) | |  |   <\__ \
# |_| \_|\___|\__| \_/\_/ \___/|_|  |_|\_\___/

networks: # 192.168.2.0/24
# System
  owasp_net:
    name: "owasp_net"
    driver: "bridge"
    ipam:
      config:
        - subnet: "192.168.2.0/24"
          ip_range: "192.168.2.0/24"
          gateway: "192.168.2.1"

# __      __   _                           
# \ \    / /  | |                          
#  \ \  / /__ | |_   _ _ __ ___   ___  ___ 
#   \ \/ / _ \| | | | | '_ ` _ \ / _ \/ __|
#    \  / (_) | | |_| | | | | | |  __/\__ \
#     \/ \___/|_|\__,_|_| |_| |_|\___||___/

# volumes:
  # placeholder

# CREATED BY Bruno Scholz
