#!/bin/bash

# Farben für das Menü
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
NC='\033[0m' # Reset Farbe

# Helper function for colored messages
print_msg() {
    echo -e "${1}${2}${NC}"
}

#############################
# Check if executed as root #
#############################
if [ "$(id -u)" -ne 0 ]; then
    print_msg "$RED" ">> This script must be run as root."
    exit 1
fi

config_controller() {
    local config_file="./components/configuration.yaml"

    if [ -f "$config_file" ]; then
        print_msg "$BLUE" ">> Showing content of $config_file:"

        # Extract services and iterate over them
        services=$(yq eval '.services | keys' "$config_file" | sed 's/- //g')

        for service in $services; do
            status=$(yq eval ".services.\"$service\"" "$config_file")
            port=$(yq eval ".ports.\"$service\"" "$config_file")
            index=$((index + 1))

            # Check service status and format output
            if [ "$status" == "yes" ]; then
                print_msg "$GREEN" "[$index] - $service: aktiv - Port: ${port:-'nicht definiert'}"
            else
                print_msg "$RED" "[$index] - $service: inaktiv"
            fi
        done

        print_msg "$BLUE" ">> Configuration file is located at: $(realpath $config_file)"
    else
        print_msg "$RED" ">> Configuration file not found."
    fi

    read -p "Press Enter to return to the menu."
}

# ASCII-Art for Menue
menu_ascii_art() {
    echo -e "${RED}"
    echo " _           _                     _                   "
    echo "| |         | |                   | |                  "
    echo "| |     __ _| |__   ___  _ __ __ _| |_ ___  _ __ _   _ "
    echo "| |    / _\` | '_ \ / _ \| '__/ _\` | __/ _ \| '__| | | |"
    echo "| |___| (_| | |_) | (_) | | | (_| | || (_) | |  | |_| |"
    echo "\_____/\__,_|_.__/ \___/|_|  \__,_|\__\___/|_|   \__, |"
    echo "                                                  __/ |"
    echo "                                                 |___/ "
    echo -e "${NC}"
}

# Funktion für das Menü
show_menu() {
    clear
    menu_ascii_art
    print_msg "$BLUE" "======================================================="
    print_msg "$YELLOW" "           Welcome to the Laboratory                 "
    print_msg "$BLUE" "======================================================="
    print_msg "$YELLOW" " > Please choose an option:"
    print_msg "$GREEN" "    1) Setup project - (run first)"
    print_msg "$GREEN" "    2) Start Laboratory"
    print_msg "$GREEN" "    3) Stop Laboratory"
    print_msg "$GREEN" "    4) Show Configuration"
    print_msg "$GREEN" "    5) Exit Laboratory"
    print_msg "$BLUE" "======================================================="
}

# Funktion für Experiment 1
setup_call() {
    ./components/setup
    read -p "Press Enter to return to the menu."
}

# Funktion für Experiment 2
start_call() {
    ./components/start
    read -p "Press Enter to return to the menu."
}

# Funktion zum Überprüfen des Equipment-Status
stop_call() {
    ./components/stop
    read -p "Press Enter to return to the menu"
}

# Hauptfunktion
main_menu() {
    chmod +x ./components/start ./components/stop ./components/setup
    while true; do
        show_menu
        read -p "Enter your choice [1-5]: " choice
        echo " "
        case $choice in
        1) setup_call ;;
        2) start_call ;;
        3) stop_call ;;
        4) config_controller ;;
        5)
            print_msg "$RED" "Exiting the Laboratory. Goodbye!"
            break
            ;;
        *)
            print_msg "$RED" "Invalid choice. Please select a valid option."
            sleep 2
            ;;
        esac
    done
}

# Skript starten
main_menu
