# CREATED BY Bruno
services:

# Metasploitable
# reference: https://hub.docker.com/r/tleemcjr/metasploitable2
  metasploitable:
    image: "tleemcjr/metasploitable2"
    container_name: "Metasploitable2"
    tty: true
    stdin_open: true
    capp_add:
      - "NET_ADMIN" # Required for networkadministration
      - "NET_RAW" # Required for packet processing
    security_opt:
      - "apparmor:unconfined"
    #command:  /bin/sh -c "/bin/services.sh && bash"
    networks: ["mtsb_net"]

#  _   _      _                      _        
# | \ | |    | |                    | |       
# |  \| | ___| |___      _____  _ __| | _____ 
# | . ` |/ _ \ __\ \ /\ / / _ \| '__| |/ / __|
# | |\  |  __/ |_ \ V  V / (_) | |  |   <\__ \
# |_| \_|\___|\__| \_/\_/ \___/|_|  |_|\_\___/

networks: # 192.168.2.0/24
# System
  mtsb_net:
    name: "mtsb_net"
    driver: "bridge"
    ipam:
      config:
        - subnet: "192.168.2.0/24"
          ip_range: "192.168.2.0/24"
          gateway: "192.168.2.1"

# __      __   _                           
# \ \    / /  | |                          
#  \ \  / /__ | |_   _ _ __ ___   ___  ___ 
#   \ \/ / _ \| | | | | '_ ` _ \ / _ \/ __|
#    \  / (_) | | |_| | | | | | |  __/\__ \
#     \/ \___/|_|\__,_|_| |_| |_|\___||___/

#volumes:
  # placeholder

# CREATED BY Bruno
