services:
  webserver:
    image: "httpd"
    container_name: "Webserver"
    ports:
      - '80:80'
    volumes:
      - default:/var/www/html/
    network: [laboratory]

volumes:
  default: # Default Volume
    name: "default"

networks:
  # Laboratory Network
  laboratory: # 192.168.2.0/24
    name: "laboratory"
    driver: "bridge"
    ipam:
      config:
        - subnet: "192.168.2.0/24"
          ip_range: "192.168.2.0/24"
          gateway: "192.168.2.1"
