# CREATED BY Bruno Scholz 
services:

#OWASP Juice-Shop
# reference: https://pwning.owasp-juice.shop/companion-guide/latest/part1/running.html
  juice-shop:
    image: "bkimminich/juice-shop"
    container_name: "OWASP-JuiceShop"
    ports:
      - "3000:3000"
    networks: ["laboratory"]

#  _   _      _                      _        
# | \ | |    | |                    | |       
# |  \| | ___| |___      _____  _ __| | _____ 
# | . ` |/ _ \ __\ \ /\ / / _ \| '__| |/ / __|
# | |\  |  __/ |_ \ V  V / (_) | |  |   <\__ \
# |_| \_|\___|\__| \_/\_/ \___/|_|  |_|\_\___/

networks:
  laboratory: # Defined in base compose file
    external: true

# __      __   _                           
# \ \    / /  | |                          
#  \ \  / /__ | |_   _ _ __ ___   ___  ___ 
#   \ \/ / _ \| | | | | '_ ` _ \ / _ \/ __|
#    \  / (_) | | |_| | | | | | |  __/\__ \
#     \/ \___/|_|\__,_|_| |_| |_|\___||___/

# volumes:
  # placeholder

# CREATED BY Bruno Scholz
