# CREATED BY Bruno
services:

# Metasploitable
# reference: https://hub.docker.com/r/tleemcjr/metasploitable2
  metasploitable:
    image: "tleemcjr/metasploitable2"
    container_name: "Metasploitable2"
    tty: true
    stdin_open: true
    cap_add:
      - "NET_ADMIN" # Required for networkadministration
      - "NET_RAW" # Required for packet processing
    security_opt:
      - "apparmor:unconfined"
    networks: ["laboratory"]

#  _   _      _                      _        
# | \ | |    | |                    | |       
# |  \| | ___| |___      _____  _ __| | _____ 
# | . ` |/ _ \ __\ \ /\ / / _ \| '__| |/ / __|
# | |\  |  __/ |_ \ V  V / (_) | |  |   <\__ \
# |_| \_|\___|\__| \_/\_/ \___/|_|  |_|\_\___/

networks:
  laboratory: # Defined in base compose file
    external: true

# __      __   _                           
# \ \    / /  | |                          
#  \ \  / /__ | |_   _ _ __ ___   ___  ___ 
#   \ \/ / _ \| | | | | '_ ` _ \ / _ \/ __|
#    \  / (_) | | |_| | | | | | |  __/\__ \
#     \/ \___/|_|\__,_|_| |_| |_|\___||___/

#volumes:
  # placeholder

# CREATED BY Bruno
