# CREATED BY Bruno Scholz 
services:

# Windows 11
# reference: https://github.com/dockur/windows
  windows:
    image: "dockurr/windows"
    container_name: "Windows11"
    environment:
      - "VERSION=11"
      - "DISK_SIZE=256G"
      - "RAM_SIZE=8G"
      - "CPU_CORES=4"
      - "REGION=de-DE"
      - "KEYBOARD=de-DE"
      - "LANGUAGE=German"
    devices:
      - "/dev/kvm"
    volumes:
      - "windows_storage:/storage"
      - "windows_share:/data"
    cap_add:
      - "NET_ADMIN"
      - "NET_RAW"
    ports:
      - "8006:8006"
      - "3390:3389/tcp"
      - "3390:3389/udp"
    stop_grace_period: "2m"
    networks: ["win_net"]

#  _   _      _                      _        
# | \ | |    | |                    | |       
# |  \| | ___| |___      _____  _ __| | _____ 
# | . ` |/ _ \ __\ \ /\ / / _ \| '__| |/ / __|
# | |\  |  __/ |_ \ V  V / (_) | |  |   <\__ \
# |_| \_|\___|\__| \_/\_/ \___/|_|  |_|\_\___/

networks: # 192.168.2.0/24
# System
  win_net:
    name: "win_net"
    driver: "bridge"
    ipam:
      config:
        - subnet: "192.168.2.0/24"
          ip_range: "192.168.2.0/24"
          gateway: "192.168.2.1"

# __      __   _                           
# \ \    / /  | |                          
#  \ \  / /__ | |_   _ _ __ ___   ___  ___ 
#   \ \/ / _ \| | | | | '_ ` _ \ / _ \/ __|
#    \  / (_) | | |_| | | | | | |  __/\__ \
#     \/ \___/|_|\__,_|_| |_| |_|\___||___/

volumes:
  windows_storage: # Windows Storage
    name: "windows_storage"
  windows_share: # Windows Share
    name: "windows_share"

# CREATED BY Bruno Scholz
