services:
  metasploitable: "yes"
  juice-shop: "yes"
  windows11: "no"
  windows7e: "yes"
  windows2022: "no"

ports: # !! DO NOT CHANGE PORTS
  metasploitable: "?"
  juice-shop: "3000"
  windows11: "8006"
  windows7e: "8007"
  windows2022: "8008"
