#!/bin/bash
# CREATED BY Bruno

# Define colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
NC='\033[0m' # Reset color

# Helper function for colored messages
print_msg() {
    echo -e "${1}${2}${NC}"
}

#############################
# Check if executed as root #
#############################
if [ "$(id -u)" -ne 0 ]; then
    print_msg "$RED" ">> This script must be run as root."
    exit 1
fi

#####################################
# Setup Docker Containers           #
#####################################
stop_containers() {
    local config_file="./components/configuration.yaml"
    print_msg "$BLUE" ">> Stopping environment..."

    if [ ! -f "$config_file" ]; then
        print_msg "$YELLOW" ">> Configuration file not found. Using default settings."
        exit 1
    fi

    # Extract service configurations from the YAML file using yq
    declare -A services=(
        ["METASPLOITABLE"]=$(yq eval '.services.METASPLOITABLE' "$config_file")
        ["JUICESHOP"]=$(yq eval '.services.JUICESHOP' "$config_file")
        ["WINDOWS11"]=$(yq eval '.services.WINDOWS11' "$config_file")
        ["WINDOWS7e"]=$(yq eval '.services.WINDOWS7e' "$config_file")
        ["WINDOWS2022"]=$(yq eval '.services.WINDOWS2022' "$config_file")
    )

    declare -A ports=(
        ["METASPLOITABLE"]=$(yq eval '.ports.METASPLOITABLE' "$config_file")
        ["JUICESHOP"]=$(yq eval '.ports.JUICESHOP' "$config_file")
        ["WINDOWS11"]=$(yq eval '.ports.WINDOWS11' "$config_file")
        ["WINDOWS7e"]=$(yq eval '.ports.WINDOWS7e' "$config_file")
        ["WINDOWS2022"]=$(yq eval '.ports.WINDOWS2022' "$config_file")
    )

    declare -A compose_files=(
        ["METASPLOITABLE"]="../docker/metasploitable.docker-compose.yml"
        ["JUICESHOP"]="../docker/juiceshop.docker-compose.yml"
        ["WINDOWS11"]="../docker/windows11.docker-compose.yml"
        ["WINDOWS7e"]="../docker/windows7e.docker-compose.yml"
        ["WINDOWS2022"]="../docker/windows2022.docker-compose.yml"
    )

    # Loop through services and stop containers if they are enabled ("yes")
    for service in "${!services[@]}"; do
        if [[ "${services[$service]}" == "yes" ]]; then
            print_msg "$GREEN" "   -> Stopping $service"
            docker-compose -f "${compose_files[$service]}" down --remove-orphans
        fi
    done

    docker-compose -f docker/base.docker-compose.yml down --remove-orphans
    print_msg "$GREEN" ">> Environment stopped successfully."
}

#################################
# Main script execution         #
#################################
main() {
    stop_containers
}

main # entrypoint