# Configfile for Laboratory
# !!NOTE: The specified port must match the port specified in the compose file
services:
  metasploitable:
    enabled: "yes"
    compose_file: "metasploitable.docker-compose.yml"
    port: "NULL"
  juice-shop:
    enabled: "no"
    compose_file: "juice-shop.docker-compose.yml"
    port: "3000"
  dvwa:
    enabled: "no"
    compose_file: "dvwa.docker-compose.yml"
    port: "3010"
  windows11:
    enabled: "no"
    compose_file: "windows11.docker-compose.yml"
    port: "8006"
  windows7e:
    enabled: "no"
    compose_file: "windows7e.docker-compose.yml"
    port: "8007"
  windows2022:
    enabled: "no"
    compose_file: "windows2022.docker-compose.yml"
    port: "8008"
