#!/bin/bash
# CREATED BY Bruno

# Define colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
NC='\033[0m' # Reset color

# Helper function for colored messages
print_msg() {
    echo -e "${1}${2}${NC}"
}

#############################
# Check if executed as root #
#############################
if [ "$(id -u)" -ne 0 ]; then
    print_msg "$RED" ">> This script must be run as root or root privileges."
    exit 1
fi

#####################################
# Stop Docker Containers            #
#####################################
stop_containers() {
    local config_file="./source/configuration.yaml"
    print_msg "$BLUE" ">> Stopping environment..."

    # Prüfen, ob die Konfigurationsdatei existiert
    if [ ! -f "$config_file" ]; then
        print_msg "$RED" ">> Error: Configuration file not found at $config_file."
        exit 1
    fi

    # Prüfen, ob yq installiert ist
    if ! command -v yq &>/dev/null; then
        print_msg "$RED" ">> Error: yq is not installed. Please run 'setup' and try again."
        exit 1
    fi

    # Alle Dienste aus der YAML-Konfiguration auslesen
    local services=$(yq eval '.services | keys' "$config_file" | sed 's/- //g')
    for service in $services; do
        local enabled=$(yq eval ".services.${service}.enabled" "$config_file")
        local compose_file=$(yq eval ".services.${service}.compose_file" "$config_file")

        if [[ "$enabled" == "yes" ]]; then
            if [ -f "docker/$compose_file" ]; then
                print_msg "$GREEN" "   -> Stopping $service"
                docker-compose -f "docker/$compose_file" down --remove-orphans || {
                    print_msg "$RED" "   -> Error stopping $service. Please check the logs."
                }
            else
                print_msg "$YELLOW" "   -> Warning: Docker Compose file for $service not found. Skipping..."
            fi
        else
            print_msg "$RED" "   -> Skipping $service"
        fi
    done

    # Basiskomponente stoppen
    if [ -f docker/basecomponent.docker-compose.yml ]; then
        docker-compose -f docker/basecomponent.docker-compose.yml down --remove-orphans || {
            print_msg "$RED" ">> Error stopping base component. Please check the logs."
        }
    else
        print_msg "$YELLOW" ">> Warning: Base component configuration file not found. Skipping..."
    fi

    print_msg "$GREEN" ">> Environment stopped successfully."
}


#################################
# Main script execution         #
#################################
main() {
    stop_containers
}

main # entrypoint
